
#Database Configuration
DATASOURCE_URL: jdbc:postgresql://localhost:5433/multi_vendor
DATASOURCE_USERNAME: username
DATASOURCE_PASSWORD: password

SERVER_PORT: 8080

#MailServer Configuration
MAIL_SERVER_HOST: localhost
MAIL_SERVER_PORT: 1025
MAIL_SERVER_USERNAME: admin
MAIL_SERVER_PASSWORD: admin

# ACTIVE_PROFILE: dev

#Application Configuration
APPLICATION_FRONTEND_URL: http://localhost:3000
APPLICATION_BACKEND_URL: http://localhost:8080
APPLICATION_EMAIL_ADDRESS: kayangejr3@gmail.com
APPLICATION_JWT_SECRET: 404E635266556A586E32723538782F413F4428472B4B6250645367566B5970
APPLICATION_JWT_EXPIRATION: 86400000

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        #show_sql: true
    database: postgresql
    #database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
  sql:
    init:
      mode: never
      continue-on-error: false
      #schema-locations: classpath:/data/schema.sql
      data-locations: classpath:/data/data.sql